name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
      - DEV
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
     dev:
        name: qa
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - name: Checkout repository
            uses: actions/checkout@v2
    
          - name: Use Python 3.8.x
            uses: actions/setup-python@v2.2.1
            with:
              python-version: 3.8.x
    
          - name: Run schemachange
            env:
              SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
              SF_USERNAME: ${{ secrets.SF_USERNAME_2 }}
              SF_ROLE: ${{ secrets.SF_ROLE }}
              SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
              SF_DATABASE: ${{ secrets.SF_QA_DATABASE}}
              SNOWFLAKE_AUTHENTICATOR: 'https://trial-6721765.okta.com'
            
            run: |
              echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
              python --version
              echo "Step 1: Installing schemachange"
              pip install schemachange
              
              echo "Step 2: Running schemachange"
              schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table


     dev2:
        name: dev 
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/DEV'
        steps:
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - name: Checkout repository
            uses: actions/checkout@v2
    
          - name: Use Python 3.8.x
            uses: actions/setup-python@v2.2.1
            with:
              python-version: 3.8.x
    
          - name: Run schemachange
            env:
              SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
              SF_USERNAME: ${{ secrets.SF_USERNAME_2 }}
              SF_ROLE: ${{ secrets.SF_ROLE }}
              SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
              SF_DATABASE: ${{ secrets.SF_DEV_DATABASE }}
              SNOWFLAKE_AUTHENTICATOR: 'https://trial-6721765.okta.com'
            run: |
              echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
              python --version
              echo "Step 1: Installing schemachange"
              pip install schemachange
              
              echo "Step 2: Running schemachange"
              schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
